### ISSUE TITLE
HID-compliant game controller to Unknown USB Device (Device Descriptor Request Failed)

### ISSUE THREAD

**Issue by Inchworm333** [4ntsu/PicoGuitar#1]
it shows up as a HID-compliant game controller when I only plug in the raspberry pi pico

when I plug in the wiitar to the pico it gets changed to an Unknown USB Device (Device Descriptor Request Failed)

How exactly would I go about fixing this???

**Comment by SkyweaverFPV** [comment]
Did you ever figure this out?

**Comment by 4ntsu** [comment]
Hi, I would say double and triple check your wiring, preferably with a multimeter in continuity mode. Also, try connecting the wiitar to the pico first, and then connecting the pico to the USB port.

**Comment by Inchworm333** [comment]
Yes, it was my wiring that was messed up.
