### ISSUE TITLE
h:4:10: fatal error: boards.h: No such file or directory

### ISSUE THREAD

**Issue by rebornshadow134** [4ntsu/PicoGuitar#3]
fatal error: boards.h: No such file or directory

**Comment by 4ntsu** [comment]
Make sure your Arduino IDE has support for the Raspberry Pi Pico installed:
- Tools > Board > Boards Manager...
- Search for "Arduino Mbed OS RP2040 Boards"
- Click "Install"

Also make sure you have the latest versions of the libraries mentioned in the guide:
- WiiChuck 0.3.3
- picogamepad 1.0.0
